application:
  debug: false
  log_level: "WARNING"

database:
  connection:
    database_path: "/app/data/stockapp.db"
    pragmas:
      threads: 8
      memory_limit: "8GB"
  pool:
    max_connections: 50

event_system:
  bus:
    max_concurrent_events: 500
    error_isolation: true

data_providers:
  market_data:
    cache_ttl: 600  # Longer cache for production
  apis:
    yahoo_finance:
      timeout: 30
    alpha_vantage:
      timeout: 30
    iex_cloud:
      timeout: 30

logging:
  level: "WARNING"
  handlers:
    console:
      enabled: true
    file:
      enabled: true
      path: "/app/logs/stockapp.log"
      max_size: "50MB"
      backup_count: 10

monitoring:
  metrics:
    enabled: true
    port: 8080
  health_check:
    enabled: true
    timeout: 10

security:
  api:
    enable_auth: true
  encryption:
    algorithm: "AES256"